import { GeneratorSettings } from '../types';

export const PIANO_TYPES: string[] = [
  'Solo Piano',
  'Ambient Piano',
  'Relaxing Piano',
  'Healing Piano',
  'Peaceful Piano',
  'Emotional Piano',
  'Romantic Piano',
  'Sleep Piano',
  'Meditation Piano',
  'Study Piano',
  'Focus Piano',
  'Cinematic Piano',
  'Background Piano',
  'Felt Piano',
  'Acoustic Piano',
];

export const CATEGORIES: string[] = [
  'Relaxation',
  'Sleep',
  'Meditation',
  'Healing',
  'Stress Relief',
  'Anxiety Relief',
  'Study',
  'Deep Focus',
  'Concentration',
  'Romantic',
  'Emotional',
  'Nature',
  'Rain',
  'Peaceful',
  'Morning',
  'Night',
  'Deep Rest',
  'Spa',
  'Wellness',
  'Mindfulness',
  'Reading',
  'Work',
  'Background Ambience',
];

export const GENRES: string[] = [
  'Ambient Piano',
  'Minimal Piano',
  'Cinematic Piano',
  'New Age',
  'Neo Soul Piano',
  'Lo-Fi Piano',
  'Jazz Piano',
  'Blues Piano',
  'Soul Piano',
  'Acoustic Piano',
  'Modern Piano',
  'Atmospheric Piano',
  'Meditative Piano',
];

export const MOODS: string[] = [
  'Calm',
  'Peaceful',
  'Relaxing',
  'Healing',
  'Melancholic',
  'Emotional',
  'Warm',
  'Dreamy',
  'Serene',
  'Hopeful',
  'Romantic',
  'Nostalgic',
  'Meditative',
  'Sleepy',
  'Deep',
  'Uplifting',
  'Intimate',
  'Gentle',
  'Reflective',
  'Soothing',
];

export const COUNTRIES: string[] = [
  'Amerika Serikat',
  'Jepang',
  'Korea Selatan',
  'Indonesia',
  'Inggris',
  'Prancis',
  'Jerman',
  'Italia',
  'Spanyol',
  'Norwegia',
  'Swedia',
  'Islandia',
  'Kanada',
  'Australia',
  'Irlandia',
];

export const DEFAULT_SETTINGS: GeneratorSettings = {
  pianoType: 'Relaxing Piano',
  categories: ['Relaxation', 'Sleep', 'Peaceful'],
  genre: 'Ambient Piano',
  moods: ['Calm', 'Peaceful', 'Serene'],
  country: 'Amerika Serikat',
};
